# This docker-compose file is only for development purposes

services:
  db:
    # TODO: postgres should deploy prisma after it is up
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basedbook
    network_mode: host
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    image: ghcr.io/nasz-elektryk/basedbook-backend
    build: .
    command: pnpm start:dev
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
