# This docker-compose file is only for development purposes

services:
  db:
    # TODO: postgres should deploy prisma after it is up
    image: ghcr.io/nasz-elektryk/basedbook-db
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basedbook
    network_mode: host
  backend:
    image: ghcr.io/nasz-elektryk/basedbook-backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: pnpm start:dev
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
